### PR TITLE
Created Localization Support

### PR DESCRIPTION
**Pull request by Xilophor**
Moved translations to En_Subtitles.cs, will add documentation on how to create new locales later.
Also added the ability for mods to add subtitles for any custom sounds - will also add documentation later.

### CODE REVIEW

**Comment by Xilophor** [comment]
Updated Contribution Instructions (to prevent confusion #2); added new usage section for mods that want to add subtitles for custom sounds - _still needs testing_; Changed Plugin Class name to help prevent conflicting class names for any mods that use this; added another method mods can add subtitles - dictionaries.

**Comment by Xilophor** [comment]
Seems like custom mod subtitles will not work as intended, as the mod would **have** to require this mod - which players may not want to use. I think it would be better to separate the actual translations over to a SubtitlesAPI which mods can then require as it's just the translations, and this mod can reference that API to get the subtitle translations.

**Comment by JanGuillermo** [comment]
> Seems like custom mod subtitles will not work as intended, as the mod would **have** to require this mod - which players may not want to use. I think it would be better to separate the actual translations over to a SubtitlesAPI which mods can then require as it's just the translations, and this mod can reference that API to get the subtitle translations. Thoughts @JanGuillermo?

Agreed, separating it out would be better if we want to expand this mod more to other mods that adds custom sounds. SubtitleAPI should be fairly lightweight and reasonable enough for other mods to add their own subtitles.

I can tackle on this, if that's ok. Localization was something else I had in mind while working on this mod

**Comment by Xilophor** [comment]
> I can tackle on this, if that's ok. Localization was something else I had in mind while working on this mod

Sure thing! (I think) I already have all of the stuff to handle localization in this - should be simple to take this and implement it into a separate API

**Comment by JanGuillermo** [comment]
> > I can tackle on this, if that's ok. Localization was something else I had in mind while working on this mod
> 
> Sure thing! (I think) I already have all of the stuff to handle localization in this - should be simple to take this and implement it into a separate API

Thank you so much, and naturally, I'll credit most of it to you 😉

**Comment by Xilophor** [comment]
Might even be able to add the API to LethalAPI - I'll check in that discord. Also with all the coding I did today, I think I need a break from this :P

**Comment by legoandmars** [comment]
> Seems like custom mod subtitles will not work as intended, as the mod would **have** to require this mod - which players may not want to use. I think it would be better to separate the actual translations over to a SubtitlesAPI which mods can then require as it's just the translations, and this mod can reference that API to get the subtitle translations. Thoughts @JanGuillermo?

Plugins that want to add subtitles could use a [BepInDependency attribute](https://docs.bepinex.dev/master/api/BepInEx.BepInDependency.html) that looks something like:

 `[BepInDependency("JustJelly.Subtitles", BepInDependency.DependencyFlags.SoftDependency)]`

and then see if it's loaded in the chainloader
`bool subtitleSupport = BepInEx.Bootstrap.Chainloader.PluginInfos.ContainsKey("JustJelly.Subtitles");`
and only add subtitles if that's true

having a separate API might end up being easier anyways though, especially if other mods end up wanting to display subtitles

**Comment by Xilophor** [comment]
Forgot about that 😅, but I do think it should definitely be exported into an API so more custom subtitle mods can be created.

Might also allow localization packs to add an ITranslationTable (which I think should be changed to cause less confusion with more broad localization), which would allow players to download a localization pack with it working.

We then wouldn't have to be constantly updating the API to support more Locales, although we should still update the API on occasion with completed or nearly-complete locales.

**Pull request closed without merging**
